export const LOL_DEFAULT_QUEUE = "RANKED_SOLO_5x5";
export const DEFAULT_TIER = "CHALLENGER";
export const DEFAULT_DIVISION = "I";

export const HIGH_TIERS_WITHOUT_DIVISIONS = new Set([
	"CHALLENGER",
	"GRANDMASTER",
	"MASTER",
]);
